### ISSUE TITLE
Does not recognize gnucash splite3 file

### ISSUE THREAD

**Issue by svHatch** [MatzeB/pygnucash#1]
Ran 'gnucash2ledger.py' as:

```
python gnucash2ledger.py example.gnucash
```

It spat out:

```
Traceback (most recent call last):
File "gnucash2ledger.py", line 10, in <module>
data = gnucash.read_file(sys.argv[1])
File "/home/scott/bin/pygnucash/gnucash.py", line 78, in read_file
for row in c.execute('SELECT guid, namespace, mnemonic, fullname FROM commodities'):
sqlite3.DatabaseError: file is encrypted or is not a database
```

Python 2.7.3
Sqlite 3.7.9
Gnucash 2.6.3

**Comment by MatzeB** [comment]
Are you sure that your file is actually an sqlite3 file? gnucash supports saving as xml or as sqlite3, try using "File->Save As" in gnucash and choose sqlite3 as data format. If you did that and it doesn't help I'd be interested in a small example file.
