### ISSUE TITLE
gnucash2ledger.py drops transactions with import data

### ISSUE THREAD

**Issue by chrisberkhout** [MatzeB/pygnucash#2]
I'm finding that transactions with extra import info are being silently dropped by `gnucash2ledger.py`.

An example of such a transaction would currently be output by Piecash's `piecash_ledger.py` like this...

```
2014/01/01 * WITHDRAWAL AT HANDYBANK MELB CTL 5 O/S 25420178 01/01/14
;OFX ext. info: |Trans type:Cash withdrawal
    Assets:Current:Westpac SAV                  -180.00 AUD ;   WITHDRAWAL AT HANDYBANK MELB CTL 5 O/S 25420178 01/01/14
    Expenses:Unspecified:AUD                     180.00 AUD
```

(Which is also not quite right, because it causes errors with ledger... I opened [an issue for that on `sdementen/piecash`](https://github.com/sdementen/piecash/issues/5)).

**Comment by MatzeB** [comment]
I am not sure what you mean by extra import info. In any case I pushed pull requests today that add the "num" field and additional descriptions from splits as comments to the export. I hope that is what you wanted.
